In [1]:
import numpy as np

In [2]:
l1 = [[1,2,3,4],[5,6,7,8]]

In [3]:
A = np.array(l1)

In [4]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
row_means = np.mean(A,axis=1)

In [6]:
row_means

array([2.5, 6.5])

In [7]:
column_means = np.mean(A,axis=0)

In [8]:
column_means

array([3., 4., 5., 6.])

In [9]:
row_means.shape

(2,)

In [10]:
A.shape

(2, 4)

In [11]:
column_means

array([3., 4., 5., 6.])

In [12]:
row_means = row_means.reshape(2,1)

In [13]:
row_means.shape

(2, 1)

In [14]:
row_means

array([[2.5],
       [6.5]])

In [15]:
row_means = row_means.reshape(1,2)

In [16]:
row_means

array([[2.5, 6.5]])

In [20]:
row_means = row_means.reshape(2,1,1,1)

In [21]:
row_means

array([[[[2.5]]],


       [[[6.5]]]])

In [22]:
column_means = column_means.reshape(1,4)

In [23]:
column_means

array([[3., 4., 5., 6.]])

In [24]:
column_means = column_means.reshape(4,1)

In [25]:
column_means

array([[3.],
       [4.],
       [5.],
       [6.]])

In [26]:
column_means = column_means.reshape(2,2)

In [27]:
column_means

array([[3., 4.],
       [5., 6.]])

In [28]:
column_means = column_means.reshape(2,2,1)

In [29]:
column_means

array([[[3.],
        [4.]],

       [[5.],
        [6.]]])

In [30]:
column_means = column_means.reshape(1,2,2)

In [31]:
column_means

array([[[3., 4.],
        [5., 6.]]])

In [32]:
column_means = column_means.reshape(2,1,2)

In [33]:
column_means

array([[[3., 4.]],

       [[5., 6.]]])

In [34]:
column_means = column_means.reshape(1,4,1)

In [35]:
column_means

array([[[3.],
        [4.],
        [5.],
        [6.]]])

In [36]:
column_means = np.mean(A,axis=0)

In [37]:
column_means

array([3., 4., 5., 6.])

In [38]:
column_means= column_means.reshape(2,-1)

In [39]:
column_means

array([[3., 4.],
       [5., 6.]])

In [40]:
column_means = column_means.reshape(4,-1)

In [41]:
column_means

array([[3.],
       [4.],
       [5.],
       [6.]])

In [42]:
column_means = column_means.reshape(-1,4)

In [43]:
column_means

array([[3., 4., 5., 6.]])

In [44]:
column_means = column_means.reshape(2,-1,2)

In [45]:
column_means.shape

(2, 1, 2)

In [46]:
column_means = column_means.reshape(1,-1,1)

In [47]:
column_means.shape

(1, 4, 1)

In [48]:
column_means

array([[[3.],
        [4.],
        [5.],
        [6.]]])

In [50]:
A.argmax(axis=1)

array([3, 3], dtype=int64)

In [51]:
A.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [52]:
B = np.random.randint(low=0,high=200,size=(2,5))

In [53]:
B

array([[114, 156, 139, 114,  26],
       [192, 108,  89,   1, 110]])

In [54]:
B.argsort()

array([[4, 0, 3, 2, 1],
       [3, 2, 1, 4, 0]], dtype=int64)

In [55]:
B.flatten()

array([114, 156, 139, 114,  26, 192, 108,  89,   1, 110])

In [57]:
B.dtype

dtype('int32')

In [58]:
B.max(axis=0)

array([192, 156, 139, 114, 110])

In [60]:
B[B < 100]

array([26, 89,  1])

In [61]:
B[:,1:4]

array([[156, 139, 114],
       [108,  89,   1]])

In [62]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.random.binomial(n=2,p=0.65,size=(10,2))

array([[2, 1],
       [1, 2],
       [2, 1],
       [1, 1],
       [1, 2],
       [0, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2]])

# we are going to talk about this in another video (np.random.multinomial)

In [67]:
np.random.randn(10,4)

array([[ 1.25085614,  1.00526079, -0.4796441 , -0.82156895],
       [ 0.47523545, -0.64777652,  0.48343981,  0.80961714],
       [-0.06497154, -0.83101609, -0.96930861,  0.90888311],
       [-1.01245722,  0.75943606, -0.34861731, -0.37717262],
       [ 0.02466837, -0.45769747,  0.46969211, -0.07315416],
       [ 1.0716407 ,  1.61241192,  0.19168326, -0.3660396 ],
       [ 2.05704161, -1.94053175, -1.4432579 ,  0.01234799],
       [-0.410794  , -0.66497006, -1.15598346,  0.49302503],
       [-0.46246741,  0.13359387,  1.23846397, -0.94340016],
       [ 0.80543585,  0.89925308, -0.3752666 , -1.16874399]])

In [68]:
np.random.normal(loc=65,scale=5,size=(100,))

array([56.38639512, 51.63397021, 62.65825018, 64.1623292 , 73.95937973,
       68.44284989, 71.03704075, 54.02339673, 69.20814349, 66.76105542,
       67.1722311 , 62.87670453, 69.67534788, 65.8768502 , 63.86297647,
       55.2329283 , 69.51397344, 63.6519926 , 55.38533034, 72.3869794 ,
       62.35714965, 69.90900151, 56.91091063, 61.49562996, 59.7897885 ,
       64.61945239, 67.8488456 , 63.50739143, 75.66026983, 65.2981821 ,
       72.48851905, 71.14509915, 61.55009592, 64.20280169, 63.17382151,
       65.78860716, 64.75913936, 71.53057983, 66.19847261, 54.60794097,
       68.78387796, 65.10357125, 65.86204624, 63.5078634 , 67.33360742,
       55.54299735, 75.43911595, 64.02014982, 63.662112  , 63.33763968,
       54.67708187, 70.35021353, 63.14743136, 66.9323636 , 69.15867512,
       58.49016136, 69.22965928, 65.15258879, 59.73163843, 55.76009033,
       57.1153548 , 63.40865275, 69.75124318, 65.84858963, 71.51367556,
       63.94425861, 57.79618428, 70.31964165, 59.57942907, 61.93

In [69]:
B

array([[114, 156, 139, 114,  26],
       [192, 108,  89,   1, 110]])

In [72]:
np.count_nonzero(B < 100,axis=1)

array([1, 2], dtype=int64)

In [73]:
random_array = np.random.randint(low=45,high=501,size=(500,2))

In [74]:
random_array.shape

(500, 2)

In [77]:
random_array = random_array.reshape(125,-1,1)

In [78]:
random_array.shape

(125, 8, 1)

In [79]:
random_array = random_array.reshape(125,1,-1)

In [80]:
random_array.shape

(125, 1, 8)

In [82]:
random_array.reshape(125,-1,4)

array([[[453, 149, 363, 189],
        [442, 451, 191, 146]],

       [[ 70, 397, 147, 356],
        [407, 310, 112, 141]],

       [[136, 296,  52, 252],
        [125, 496, 105, 386]],

       [[453,  51, 238, 156],
        [220, 300,  69, 256]],

       [[131,  85, 391, 244],
        [374, 413, 301, 466]],

       [[178, 469, 234, 148],
        [439,  79, 275, 180]],

       [[141, 237, 175, 284],
        [191, 129, 331, 311]],

       [[348, 409, 410, 259],
        [267, 125, 238, 244]],

       [[331, 458, 495, 492],
        [396, 167, 478, 201]],

       [[476, 216, 397, 368],
        [ 89, 299, 451, 372]],

       [[227, 329, 416, 498],
        [179, 149, 391, 142]],

       [[350, 444,  77, 416],
        [421, 287, 225, 319]],

       [[ 81, 148, 168, 244],
        [232, 231, 452, 163]],

       [[ 57, 143, 301, 288],
        [317, 329, 163, 132]],

       [[173, 161, 486, 279],
        [ 48, 311,  57, 313]],

       [[ 96, 153, 498,  55],
        [417, 448, 266, 183]],

       [